version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    networks:
      - my-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    environment:
      - DATABASE_URL=mysql+pymysql://dbuser:dbpassword@mysql:3306/mydatabase
    ports:
      - "8000:80"
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - my-network
    volumes:
      - ./app:/code/app

  nginx:
    build: ./
    # image: jasonbigcow/oauth2-vue3-nginx
    ports:
      - 80:8080
    restart: always
    depends_on:
      - fastapi
    volumes:
      - ./nginx:/etc/nginx/conf.d

networks:
  my-network:
    name: fastapi_vue_network